/* AUTO-GENERATED FILE.  DO NOT MODIFY.
 *
 * This class was automatically generated by the
 * aapt tool from the resource data it found.  It
 * should not be modified by hand.
 */

package uk.co.mybuzztechnologies.androidwidgettest;

public final class R {
    public static final class attr {
    }
    public static final class dimen {
        /** 
Refer to App Widget Documentation for margin information
http://developer.android.com/guide/topics/appwidgets/index.html#CreatingLayout
    

Refer to App Widget Documentation for margin information
http://developer.android.com/guide/topics/appwidgets/index.html#CreatingLayout
    
         */
        public static final int widget_margin=0x7f050000;
    }
    public static final class drawable {
        public static final int example_appwidget_preview=0x7f020000;
    }
    public static final class id {
        public static final int texty_texty=0x7f070000;
    }
    public static final class layout {
        public static final int widget01=0x7f030000;
    }
    public static final class string {
        public static final int add_widget=0x7f060002;
        public static final int app_name=0x7f060000;
        public static final int appwidget_text=0x7f060001;
    }
    public static final class xml {
        public static final int widget01_info=0x7f040000;
    }
}
